# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dfd55bc1214a471506013f570f9af8fbc5ebf6ff78918ec5651d8bdfdf35c54b02819d0991d3eb378ec1c894952593e667ee3babad7a6945aa8eef06c0a2fd8

test:
  secret_key_base: 29200eb9d5c5790d34b6807326703ac2e476589ca5b64d2d854c0b19cec8d3d605e1731c400199976c5306a0e48eb4828e5f39959004d2d3353a4e3b4039cfad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
